### ISSUE TITLE
Did changing IP address lose me?

### ISSUE THREAD

**Issue by stephenpurkiss** [lightningrodlabs/moss#87]
Sometimes I like to have my video calls with my support workers in the mountains because - well - because I can 😎. Last time I connected via Zoom but this time I thought I'd take my laptop so it would also be a surprise. What happened though was 10 minutes of us waiting wondering what was up with the other person.

Turned out neither of us could see the other, despite several restarts of Moss.

The only thing I can think is because I was connecting via my phone's connection it was a different IP address and couldn't find it. So how does one deal with this, if at all? Surely not sending another group invite?

Or is this just how it works, I'm a different agent if I move.

Meanwhile...

![IMG_3122](https://github.com/user-attachments/assets/aac6695c-f0da-45e8-81ee-35b5a7f6dec0)

**Comment by matthme** [comment]
> Turned out neither of us could see the other, despite several restarts of Moss

Can you elaborate on what you mean by "not seeing each other"? Was this in an existing group where things previously worked or was this upon creating/joining a new group and the group info never got synchronized?

Changing the IP should not affect anything in general, at least not if Moss gets restarted. There are some known issues still where switching networks *while* holochain is running may interrupt ongoing connections but they should get re-established when restarting Moss (and thereby the underlying holochain process).

**Comment by stephenpurkiss** [comment]
> Can you elaborate on what you mean by "not seeing each other"?

Existing group, been using it successfully for a month now - mostly for Presence, a lot of KanDo, and Notebooks as had multiple issues with Sweet and Notebooks is super-simple so works great!

I have a Macbook M3 Air & although I know it works in the background when I close the lid, AFAIK that's only if you have the power plugged in which of course I didn't so not sure it would've switched networks while Holochain was running.

I might be able to test it in my flat by switching from broadband to mobile, but the reception is bad around here so like now I see it's on WiFi calling cos there's no signal. 

As for not being able to see each other - she couldn't see I was online in the group and I couldn't see her online either, and we both restarted Moss multiple times.

Luckily I took a screenshot - Elizabeth has two profiles as mostly uses a Windows laptop but couldn't see the formatting icons in Sweet so tried from her Mac laptop which meant setting up a different profile. Which reminds me, I never noted that in the [calcy issue queue](https://github.com/lightningrodlabs/calcy/issues) where I noted a few other issues. I do have it in my KanDo Moss Issues board though so will do.

Anyway, so as you can see, she wasn't online, but was.

I still can't get my head around how the discovery works - maybe now I have Claude and OpenAI subscriptions I'll ask them sometime, see what they say, or get [Google NotebookLM](https://notebooklm.google.com) to make a podcast about it, did that for my project and it's awesome!

<img width="1440" alt="offline" src="https://github.com/user-attachments/assets/49e55dbb-10cf-4fc8-b238-7b9a4e891327">

**Comment by matthme** [comment]
Okay thank you, that helps as context. So it sounds that connections did indeed not succeed at the holochain level. It is known that at the moment any network interruptions also interrupt connection with other holochain peers for at least 10-15 minutes. That's a bug that needs to be addressed in holochain. This can happen if you close the lid of your laptop (depending on your specific laptop settings as to what happens when you close the lid). It can also happen if the internet connection is flaky in general and you intermittently lose connection to the internet.

You said though that you both restarted Moss multiple times which should at least make it work temporarily I would expect. Unless your internet connection was really unstable. So I'm also wondering whether it might have had something to do with a specific network constellation which prevented holochain's underlying webRTC from connecting at all.

If you want you can drop your logs again [here](https://drive.switch.ch/index.php/s/WnSuSSQxcSjGNlq) and let me know at what time/day roughly that occurred and I can check whether I see anything that would hint to such a networking problem.
